### ISSUE TITLE
Unable to pull docker

### ISSUE THREAD

**Issue by harmanpreet93** [sladebot/deepvo#5]
Hi @sladebot 

I'm unable to pull docker from [docker hub](https://store.docker.com/community/images/souranilsbu/tf-opencv3).  

I'm getting the following error:  

> Using default tag: latest
> Error response from daemon: manifest for souranilsbu/tf-opencv3:latest not found

Can you please share any other docker image? 

Thanks

**Comment by harmanpreet93** [comment]
Since this image just had tensorflow v1.3 and OpenCV 3.0, we installed them natively.

**Comment by MrEliptik** [comment]
Hi, I'm having trouble running the makefile and so I wanted to use directly the docker image. Is it possible to have it working? 
@harmanpreet93 have you succeeded in using this project?
